# Generated by Django 4.2.5 on 2023-10-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="liked_recipes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_recipes", to="recipes.recipe"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
