# Generated by Django 4.2.5 on 2023-10-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_recipe_likes"),
        ("users", "0002_customuser_bio_customuser_liked_recipes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="liked_recipes",
        ),
        migrations.AddField(
            model_name="customuser",
            name="fav_recipes",
            field=models.ManyToManyField(
                blank=True, related_name="fav_recipes", to="recipes.recipe"
            ),
        ),
    ]
