# Generated by Django 4.2.5 on 2023-10-28 00:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_likedrecipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="fav_recipes",
        ),
        migrations.DeleteModel(
            name="LikedRecipe",
        ),
    ]
