# Generated by Django 4.2.5 on 2023-10-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_customuser_fav_recipes_delete_likedrecipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="pic",
            field=models.ImageField(
                blank=True,
                default="no_picture.jpg",
                null=True,
                upload_to="profile_pics",
            ),
        ),
    ]
