# Generated by Django 4.2.5 on 2023-10-30 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("ingredients", models.CharField(max_length=255)),
                ("cooking_time", models.IntegerField()),
                (
                    "pic",
                    models.ImageField(default="no_picture.jpg", upload_to="recipes"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pic",
                    models.ImageField(
                        blank=True,
                        default="no_picture.jpg",
                        null=True,
                        upload_to="profile_pics",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "fav_recipes",
                    models.ManyToManyField(
                        blank=True, related_name="favorited_by", to="recipes.recipe"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
