# Generated by Django 4.2.5 on 2023-10-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("ingredients", models.CharField(max_length=255)),
                ("cooking_time", models.IntegerField()),
                (
                    "pic",
                    models.ImageField(default="no_picture.jpg", upload_to="recipes"),
                ),
            ],
        ),
    ]
