# Generated by Django 4.2.5 on 2023-11-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="fav_recipes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="favorited_by", to="recipes.recipe"
            ),
        ),
    ]
