# Generated by Django 4.2.5 on 2023-11-02 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_userprofile_fav_recipes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="fav_recipes",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="fav_recipes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.recipe",
            ),
        ),
    ]
