# Generated by Django 4.2.5 on 2023-11-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_remove_userprofile_fav_recipes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="fav_recipes",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="fav_recipes",
            field=models.ManyToManyField(blank=True, null=True, to="recipes.recipe"),
        ),
    ]
