# Generated by Django 4.2.5 on 2023-11-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_remove_userprofile_fav_recipes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="fav_recipes",
            field=models.ManyToManyField(blank=True, to="recipes.recipe"),
        ),
    ]
