# Generated by Django 4.2.5 on 2023-10-20 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_instruction_recipe_alter_recipe_instructions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="instructions",
        ),
        migrations.DeleteModel(
            name="Instruction",
        ),
    ]
